In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
#creating numpy array
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [18]:
#creating numpy array
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [17]:
b.dtype

dtype('float64')

In [19]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
c.dtype

dtype('complex128')

In [21]:
#fill zeroes
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
#fill ones
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
#uninitialized, output may vary
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [26]:
np.arange( 0, 2, 0.3 )   

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [29]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [30]:
print(a)

[2 3 4]


In [34]:
b = np.arange(12).reshape(4,3)    
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
c = np.arange(24).reshape(2,3,4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [38]:
np.set_printoptions(threshold=np.nan)

In [44]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a-b

array([20, 29, 38, 47])

In [45]:
b**2

array([0, 1, 4, 9])

In [46]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [47]:
a<35

array([ True,  True, False, False])

In [48]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )
A * B                  

array([[2, 0],
       [0, 4]])

In [49]:
A @ B

array([[5, 4],
       [3, 4]])

In [50]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [51]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3

In [52]:
b += a

In [53]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [54]:
b

array([[3.85798706, 3.97673538, 3.07372237],
       [3.20298647, 3.7206308 , 3.24600298]])

In [55]:
#Indexing, Slicing and Iterating¶
a = np.arange(10)**3

In [56]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [57]:
a[2]

8

In [58]:
a[2:5]

array([ 8, 27, 64])

In [59]:
a[:6:2] = -1000 

In [60]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [61]:
a[ : :-1]   

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [62]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [64]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [65]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [66]:
def f(x,y):
     return 10*x+y

In [67]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [68]:
b[2,3]

23

In [74]:
b[0:5, 1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [75]:
b[ : ,1] # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [76]:
b[1:3, : ] # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [77]:
b[-1]  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [78]:
for element in b.flat:
     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [79]:
a = np.floor(10*np.random.random((3,4)))
a

array([[3., 1., 8., 9.],
       [4., 6., 4., 3.],
       [0., 8., 5., 6.]])

In [80]:
a.shape

(3, 4)

In [81]:
a.ravel()

array([3., 1., 8., 9., 4., 6., 4., 3., 0., 8., 5., 6.])

In [82]:
a.reshape(6,2)

array([[3., 1.],
       [8., 9.],
       [4., 6.],
       [4., 3.],
       [0., 8.],
       [5., 6.]])

In [83]:
a.T

array([[3., 4., 0.],
       [1., 6., 8.],
       [8., 4., 5.],
       [9., 3., 6.]])

In [85]:
#Several arrays can be stacked together along different axes:

a = np.floor(10*np.random.random((2,2)))
a


array([[4., 3.],
       [4., 2.]])

In [86]:
b = np.floor(10*np.random.random((2,2)))
b


array([[2., 0.],
       [7., 3.]])

In [87]:
np.vstack((a,b))


array([[4., 3.],
       [4., 2.],
       [2., 0.],
       [7., 3.]])

In [88]:
np.hstack((a,b))

array([[4., 3., 2., 0.],
       [4., 2., 7., 3.]])

In [89]:
np.column_stack((a,b))  

array([[4., 3., 2., 0.],
       [4., 2., 7., 3.]])

In [90]:
d = a.copy() 

In [92]:
#Linear Algebra

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
a.transpose()

[[1. 2.]
 [3. 4.]]


array([[1., 3.],
       [2., 4.]])

In [93]:
np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u


array([[1., 0.],
       [0., 1.]])

In [95]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j        # matrix product


array([[-1.,  0.],
       [ 0., -1.]])

In [96]:
np.trace(u)  # trace


2.0

In [97]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [98]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [102]:
x = np.arange(0,10,2)                     # x=([0,2,4,6,8])
y = np.arange(5)                          # y=([0,1,2,3,4])
m = np.vstack([x,y])                      # m=([[0,2,4,6,8],
                                          #     [0,1,2,3,4]])
xy = np.hstack([x,y])                     # xy =([0,2,4,6,8,0,1,2,3,4])

In [103]:
a = [1,4,6]
b = [1,2,3]  

In [105]:
print(np.corrcoef(a,b))

[[1.         0.99339927]
 [0.99339927 1.        ]]
